// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFh-Wsy9WQvRbnO2zK3-tBWo2W8JpukiU',
    appId: '1:1074736949567:web:712bb96aca8881a46a8b8a',
    messagingSenderId: '1074736949567',
    projectId: 'hostel-management-26fc1',
    authDomain: 'hostel-management-26fc1.firebaseapp.com',
    storageBucket: 'hostel-management-26fc1.firebasestorage.app',
    measurementId: 'G-HF120K59F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfQQWeDT6Tjq365ua9TZMfgAMp0N48Uk',
    appId: '1:1074736949567:android:a088d8d4e91582516a8b8a',
    messagingSenderId: '1074736949567',
    projectId: 'hostel-management-26fc1',
    storageBucket: 'hostel-management-26fc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYgVbRBxoF0Y5iwq8TSpitldmY7MCzmr4',
    appId: '1:1074736949567:ios:d70190c242bcaee96a8b8a',
    messagingSenderId: '1074736949567',
    projectId: 'hostel-management-26fc1',
    storageBucket: 'hostel-management-26fc1.firebasestorage.app',
    iosBundleId: 'com.example.hostelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYgVbRBxoF0Y5iwq8TSpitldmY7MCzmr4',
    appId: '1:1074736949567:ios:d70190c242bcaee96a8b8a',
    messagingSenderId: '1074736949567',
    projectId: 'hostel-management-26fc1',
    storageBucket: 'hostel-management-26fc1.firebasestorage.app',
    iosBundleId: 'com.example.hostelManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFh-Wsy9WQvRbnO2zK3-tBWo2W8JpukiU',
    appId: '1:1074736949567:web:97a88ac2a49639d16a8b8a',
    messagingSenderId: '1074736949567',
    projectId: 'hostel-management-26fc1',
    authDomain: 'hostel-management-26fc1.firebaseapp.com',
    storageBucket: 'hostel-management-26fc1.firebasestorage.app',
    measurementId: 'G-RWN97B4MQG',
  );
}
